/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FixtureErrorRouteImport } from './routes/fixture-error'
import { Route as DetailRouteImport } from './routes/detail'
import { Route as IndexRouteImport } from './routes/index'

const FixtureErrorRoute = FixtureErrorRouteImport.update({
  id: '/fixture-error',
  path: '/fixture-error',
  getParentRoute: () => rootRouteImport,
} as any)
const DetailRoute = DetailRouteImport.update({
  id: '/detail',
  path: '/detail',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/detail': typeof DetailRoute
  '/fixture-error': typeof FixtureErrorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/detail': typeof DetailRoute
  '/fixture-error': typeof FixtureErrorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/detail': typeof DetailRoute
  '/fixture-error': typeof FixtureErrorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/detail' | '/fixture-error'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/detail' | '/fixture-error'
  id: '__root__' | '/' | '/detail' | '/fixture-error'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DetailRoute: typeof DetailRoute
  FixtureErrorRoute: typeof FixtureErrorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/fixture-error': {
      id: '/fixture-error'
      path: '/fixture-error'
      fullPath: '/fixture-error'
      preLoaderRoute: typeof FixtureErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/detail': {
      id: '/detail'
      path: '/detail'
      fullPath: '/detail'
      preLoaderRoute: typeof DetailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DetailRoute: DetailRoute,
  FixtureErrorRoute: FixtureErrorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
