import { DEFAULT_KEY_HOLD_DURATION_MS, INPUT_FOCUS_ACTIVATION_DELAY_MS } from "../src/constants.js";

export { REACT_GRAB_ATTRIBUTE_NAME as ATTRIBUTE_NAME } from "../src/utils/react-grab-attribute-name.js";
export { Z_INDEX_OVERLAY } from "../src/constants.js";

export const KEYBOARD_ACTIVATION_TIMER_BUFFER_MS = 50;
export const KEYBOARD_ACTIVATION_SETTLE_DELAY_MS =
  DEFAULT_KEY_HOLD_DURATION_MS +
  INPUT_FOCUS_ACTIVATION_DELAY_MS +
  KEYBOARD_ACTIVATION_TIMER_BUFFER_MS;
export const SHIFT_LABEL_CLICK_ANCHOR_RATIO = 0.25;
export const SHIFT_LABEL_SECOND_CLICK_ANCHOR_RATIO = 0.75;
export const SHIFT_LABEL_ANCHORED_COUNT = 2;
export const SHIFT_LABEL_POSITION_TOLERANCE_PX = 2;
export const SHIFT_LABEL_MOUSE_MOVE_INSET_PX = 10;
export const SHIFT_LABEL_SETTLE_DELAY_MS = 120;
export const SHIFT_DRAG_PREVIEW_OUTSET_PX = 10;
export const SHIFT_DRAG_PREVIEW_STEP_COUNT = 6;
export const HOST_STYLE_DRAG_DISTANCE_PX = 100;
export const HOST_STYLE_DRAG_STEP_COUNT = 4;
export const SHIFT_PENDING_HOVER_STEP_COUNT = 8;
export const POINTER_SETTLE_DELAY_MS = 32;
export const IFRAME_TEST_POINTER_ID = 1;
export const IFRAME_SCROLL_SETTLE_DELAY_MS = 150;
export const IFRAME_SCROLL_DELTA_Y_PX = 200;
export const IFRAME_RESIZE_TEST_VIEWPORT_WIDTH_PX = 1100;
export const IFRAME_RESIZE_TEST_VIEWPORT_HEIGHT_PX = 700;
export const SCALED_IFRAME_EXPECTED_BORDER_RADIUS = "7.2px 10.8px / 14.4px 18px";
export const NON_UNIFORM_SCALED_IFRAME_EXPECTED_BORDER_RADIUS = "6px 9px / 8px 10px";
export const SHADOW_HOVER_BACKGROUND_COLOR = "rgb(14, 165, 233)";
export const SHADOW_FRAME_FOCUS_OUTLINE_COLOR = "rgb(168, 85, 247)";
export const FRAMEWORK_COPY_RETRY_TIMEOUT_MS = 20_000;
export const UI_STATE_TIMEOUT_MS = 10_000;
export const THREE_CANVAS_VERTICAL_CENTER_RATIO = 0.5;
export const THREE_DRAG_SELECTION_OUTSET_PX = 5;
export const THREE_JS_FRAME_COUNT_WINDOW_PROPERTY = "__REACT_GRAB_THREE_JS_FRAME_COUNT__";
export const THREE_FRAME_COUNT_WINDOW_PROPERTY = "__REACT_GRAB_THREE_FRAME_COUNT__";
export const THREE_ELAPSED_TIME_WINDOW_PROPERTY = "__REACT_GRAB_THREE_ELAPSED_TIME__";
export const THREE_LEFT_OBJECT_HORIZONTAL_RATIO = 0.39;
export const THREE_OBJECT_POINTER_NUDGE_PX = 1;
export const THREE_RIGHT_OBJECT_HORIZONTAL_RATIO = 0.61;
export const THREE_RENDER_FREEZE_OBSERVATION_MS = 250;
export const THREE_RENDER_FREEZE_SETTLE_MS = 100;
export const THREE_SELECTION_MAX_CANVAS_WIDTH_RATIO = 0.5;
export const FINITE_RAF_SEQUENCE_FRAME_COUNT = 10;
export const FINITE_RAF_SEQUENCE_REPETITION_COUNT = 2;
export const FINITE_RAF_SEQUENCE_TIMEOUT_MS = 1_000;
export const RAF_LOOP_SETTLE_MS = 200;
